### ISSUE TITLE
Ajouter le calendrier partagé "Myne evènements"

### ISSUE THREAD

**Issue by CharlotteRizzo** [La-MYNE/Website#56]
remplacer l'url existante dans https://www.lamyne.org/agenda/ par l'agenda "myne évènement" qui est partagé dans le nextcloud à cette url : https://cloud.lamyne.org/index.php/apps/calendar/p/gm3XbT4AEaekAiWm/La-MYNE-evenements

(si possible de fusionner 2 calendriers on conserve les 2 mais sinon on garde seulement myne evenements)

**Comment by oncletom** [comment]
@unteem je crois que ça ne s'affiche pas car les entêtes CSP de `cloud.lamyne.org` ne permettent pas aux contenus d'être embarqués sous forme de frame sur lamyne.org.

<img width="872" alt="capture d ecran 2018-04-25 a 16 55 26" src="https://user-images.githubusercontent.com/138627/39254079-92dc6356-48a9-11e8-92ca-c2660f01dc50.png">

Chais plus quelles sont les options exactes à rajouter par contre 😅

**Comment by unteem** [comment]
Yep le pb venait des http headers du NC... C'est modifie.
